### PR TITLE
feat: add support for kubescape json as input

### LINKED ISSUE #208: [REQ] support for kubescape json as input
### What kind of request is this?

New feature

### What is your request or suggestion?

copa currently supports patching images using report generated by Trivy in JSON format
**FEATURE:**
add support to copa for patching images using report format generated by [Kubescape](https://github.com/kubescape/kubescape) as well, in JSON format.

### PR DESCRIPTION
**Pull request by anubhav06**
Added support to copa to accept [Kubescape](https://github.com/kubescape/kubescape) JSON as input.
Now, if we provide to copa as input, the image vulnerability report generated by Kubescape in JSON format, copa is able to patch the images by reading that report.

Closes #208 

cc: @craigbox

### CODE REVIEW

**Comment by anubhav06** [comment]
Hello maintainers -- 
I just wanted to check the status of this PR. Is there any feedback or additional information needed for its consideration?

**Comment by salaxander** [comment]
Hey @anubhav06 - sorry about the delay on this! We're currently discussing a design for Copa on modular plugins, and we think Kubescape would probably be a good fit for this. Give us a little more time to figure out the design, and we'll let you know what's next.

Thank you for working on this!!

**Comment by anubhav06** [comment]
Great, no problem! Thanks for letting me know :)

**Comment by salaxander** [comment]
Hey there @anubhav06! Mind if we close this PR in favor of a plugin?

**Comment by anubhav06** [comment]
yes! sorry I forgot about closing this

**Pull request closed without merging**
